/* Generated By:JavaCC: Do not edit this line. JavaSwiftConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaSwiftConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int UPPER_LETTER = 6;
  /** RegularExpression Id. */
  int LOWER_LETTER = 7;
  /** RegularExpression Id. */
  int UNDERSCORE = 8;
  /** RegularExpression Id. */
  int ESCAPE_CHARACTERS = 9;
  /** RegularExpression Id. */
  int SURROGATE_PAIR_CODE = 10;
  /** RegularExpression Id. */
  int DIGIT = 11;
  /** RegularExpression Id. */
  int BINARY_DIGIT_BEGIN = 12;
  /** RegularExpression Id. */
  int BINARY_DIGIT = 13;
  /** RegularExpression Id. */
  int OCTAL_DIGIT_BEGIN = 14;
  /** RegularExpression Id. */
  int OCTAL_DIGIT = 15;
  /** RegularExpression Id. */
  int HEXADECIMAL_DIGIT_BEGIN = 16;
  /** RegularExpression Id. */
  int HEXADECIMAL_DIGIT = 17;
  /** RegularExpression Id. */
  int PLUS = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int ASSIGN = 20;
  /** RegularExpression Id. */
  int E = 21;
  /** RegularExpression Id. */
  int P = 22;
  /** RegularExpression Id. */
  int STAR = 23;
  /** RegularExpression Id. */
  int PERCENT = 24;
  /** RegularExpression Id. */
  int MORE_OR_EQUALS = 25;
  /** RegularExpression Id. */
  int LESS_OR_EQUALS = 26;
  /** RegularExpression Id. */
  int EQUALS = 27;
  /** RegularExpression Id. */
  int TRUE = 28;
  /** RegularExpression Id. */
  int FALSE = 29;
  /** RegularExpression Id. */
  int NIL = 30;
  /** RegularExpression Id. */
  int SHARP_FILE = 31;
  /** RegularExpression Id. */
  int SHARP_LINE = 32;
  /** RegularExpression Id. */
  int COLUMN = 33;
  /** RegularExpression Id. */
  int FUNCTION = 34;
  /** RegularExpression Id. */
  int COLOR_LITERAL = 35;
  /** RegularExpression Id. */
  int RED = 36;
  /** RegularExpression Id. */
  int GREEN = 37;
  /** RegularExpression Id. */
  int BLUE = 38;
  /** RegularExpression Id. */
  int ALPHA = 39;
  /** RegularExpression Id. */
  int FILE_LITERAL = 40;
  /** RegularExpression Id. */
  int IMAGE_LITERAL = 41;
  /** RegularExpression Id. */
  int RESOURCE_NAME = 42;
  /** RegularExpression Id. */
  int OPERATOR_HEAD = 43;
  /** RegularExpression Id. */
  int OPERATOR_CHARACTER = 44;
  /** RegularExpression Id. */
  int ANY = 45;
  /** RegularExpression Id. */
  int ARROW_RIGHT = 46;
  /** RegularExpression Id. */
  int INOUT = 47;
  /** RegularExpression Id. */
  int THROWS = 48;
  /** RegularExpression Id. */
  int RETHROWS = 49;
  /** RegularExpression Id. */
  int CAPITAL_TYPE = 50;
  /** RegularExpression Id. */
  int CAPITAL_PROTOCOL = 51;
  /** RegularExpression Id. */
  int CLASS = 52;
  /** RegularExpression Id. */
  int TRY = 53;
  /** RegularExpression Id. */
  int AS = 54;
  /** RegularExpression Id. */
  int IS = 55;
  /** RegularExpression Id. */
  int SELF = 56;
  /** RegularExpression Id. */
  int INIT = 57;
  /** RegularExpression Id. */
  int SUPER = 58;
  /** RegularExpression Id. */
  int IN = 59;
  /** RegularExpression Id. */
  int WEAK = 60;
  /** RegularExpression Id. */
  int UNOWNED = 61;
  /** RegularExpression Id. */
  int SAFE = 62;
  /** RegularExpression Id. */
  int UNSAFE = 63;
  /** RegularExpression Id. */
  int SELECTOR = 64;
  /** RegularExpression Id. */
  int GETTER = 65;
  /** RegularExpression Id. */
  int SETTER = 66;
  /** RegularExpression Id. */
  int KEY_PATH = 67;
  /** RegularExpression Id. */
  int TYPE = 68;
  /** RegularExpression Id. */
  int OF = 69;
  /** RegularExpression Id. */
  int LET = 70;
  /** RegularExpression Id. */
  int VAR = 71;
  /** RegularExpression Id. */
  int WHILE = 72;
  /** RegularExpression Id. */
  int FOR = 73;
  /** RegularExpression Id. */
  int CASE = 74;
  /** RegularExpression Id. */
  int REPEAT = 75;
  /** RegularExpression Id. */
  int BREAK = 76;
  /** RegularExpression Id. */
  int CONTINUE = 77;
  /** RegularExpression Id. */
  int IF = 78;
  /** RegularExpression Id. */
  int ELSE = 79;
  /** RegularExpression Id. */
  int SWITCH = 80;
  /** RegularExpression Id. */
  int DEFAULT_1 = 81;
  /** RegularExpression Id. */
  int WHERE = 82;
  /** RegularExpression Id. */
  int GUARD = 83;
  /** RegularExpression Id. */
  int FALLTHROUGH = 84;
  /** RegularExpression Id. */
  int RETURN = 85;
  /** RegularExpression Id. */
  int THROW = 86;
  /** RegularExpression Id. */
  int DEFER = 87;
  /** RegularExpression Id. */
  int DO = 88;
  /** RegularExpression Id. */
  int CATCH = 89;
  /** RegularExpression Id. */
  int SHARP_IF = 90;
  /** RegularExpression Id. */
  int SHARP_ELSEIF = 91;
  /** RegularExpression Id. */
  int SHARP_ELSE = 92;
  /** RegularExpression Id. */
  int SHARP_ENDIF = 93;
  /** RegularExpression Id. */
  int OS = 94;
  /** RegularExpression Id. */
  int ARCH = 95;
  /** RegularExpression Id. */
  int SWIFT = 96;
  /** RegularExpression Id. */
  int MAC_OS = 97;
  /** RegularExpression Id. */
  int IOS = 98;
  /** RegularExpression Id. */
  int WATCH_OS = 99;
  /** RegularExpression Id. */
  int TV_OS = 100;
  /** RegularExpression Id. */
  int I_386 = 101;
  /** RegularExpression Id. */
  int X_86_64 = 102;
  /** RegularExpression Id. */
  int ARM = 103;
  /** RegularExpression Id. */
  int ARM_64 = 104;
  /** RegularExpression Id. */
  int SOURCE_LOCATION = 105;
  /** RegularExpression Id. */
  int FILE = 106;
  /** RegularExpression Id. */
  int LINE = 107;
  /** RegularExpression Id. */
  int SHARP_AVAILABLE = 108;
  /** RegularExpression Id. */
  int IOS_APP_EXT = 109;
  /** RegularExpression Id. */
  int MAC_OS_APP_EXT = 110;
  /** RegularExpression Id. */
  int IMPORT = 111;
  /** RegularExpression Id. */
  int TYPE_ALIAS = 112;
  /** RegularExpression Id. */
  int ENUM = 113;
  /** RegularExpression Id. */
  int PROTOCOL = 114;
  /** RegularExpression Id. */
  int FUNC = 115;
  /** RegularExpression Id. */
  int GET = 116;
  /** RegularExpression Id. */
  int SET = 117;
  /** RegularExpression Id. */
  int WILL_SET = 118;
  /** RegularExpression Id. */
  int DID_SET = 119;
  /** RegularExpression Id. */
  int INDIRECT = 120;
  /** RegularExpression Id. */
  int STRUCT = 121;
  /** RegularExpression Id. */
  int FINAL = 122;
  /** RegularExpression Id. */
  int ASSOCIATED_TYPE = 123;
  /** RegularExpression Id. */
  int DEINIT = 124;
  /** RegularExpression Id. */
  int EXTENSION = 125;
  /** RegularExpression Id. */
  int SUBSCRIPT = 126;
  /** RegularExpression Id. */
  int PREFIX = 127;
  /** RegularExpression Id. */
  int POSTFIX = 128;
  /** RegularExpression Id. */
  int OPERATOR = 129;
  /** RegularExpression Id. */
  int PRECEDENCE_GROUP = 130;
  /** RegularExpression Id. */
  int HIGHER_THAN = 131;
  /** RegularExpression Id. */
  int LOWER_THAN = 132;
  /** RegularExpression Id. */
  int ASSIGNMENT = 133;
  /** RegularExpression Id. */
  int ASSOCIATIVITY = 134;
  /** RegularExpression Id. */
  int LEFT = 135;
  /** RegularExpression Id. */
  int RIGHT = 136;
  /** RegularExpression Id. */
  int NONE = 137;
  /** RegularExpression Id. */
  int CONVENIENCE = 138;
  /** RegularExpression Id. */
  int DYNAMIC = 139;
  /** RegularExpression Id. */
  int INFIX = 140;
  /** RegularExpression Id. */
  int LAZY = 141;
  /** RegularExpression Id. */
  int OPTIONAL = 142;
  /** RegularExpression Id. */
  int OVERRIDE = 143;
  /** RegularExpression Id. */
  int REQUIRED = 144;
  /** RegularExpression Id. */
  int STATIC = 145;
  /** RegularExpression Id. */
  int PRIVATE = 146;
  /** RegularExpression Id. */
  int FILEPRIVATE = 147;
  /** RegularExpression Id. */
  int INTERNAL = 148;
  /** RegularExpression Id. */
  int PUBLIC = 149;
  /** RegularExpression Id. */
  int OPEN = 150;
  /** RegularExpression Id. */
  int MUTATING = 151;
  /** RegularExpression Id. */
  int NON_MUTATING = 152;
  /** RegularExpression Id. */
  int DOT = 153;
  /** RegularExpression Id. */
  int THREE_DOTS = 154;
  /** RegularExpression Id. */
  int COMMA = 155;
  /** RegularExpression Id. */
  int SEMICOLON = 156;
  /** RegularExpression Id. */
  int COLON = 157;
  /** RegularExpression Id. */
  int QUESTION_MARK = 158;
  /** RegularExpression Id. */
  int EXCLAMATION_MARK = 159;
  /** RegularExpression Id. */
  int SLASH = 160;
  /** RegularExpression Id. */
  int BACK_SLASH = 161;
  /** RegularExpression Id. */
  int DOLLAR = 162;
  /** RegularExpression Id. */
  int AMPERSAND = 163;
  /** RegularExpression Id. */
  int DBL_AMPERSAND = 164;
  /** RegularExpression Id. */
  int OR = 165;
  /** RegularExpression Id. */
  int DBL_OR = 166;
  /** RegularExpression Id. */
  int AT = 167;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 168;
  /** RegularExpression Id. */
  int CLOSED_BRACKET = 169;
  /** RegularExpression Id. */
  int OPEN_SQUARE_BRACKET = 170;
  /** RegularExpression Id. */
  int CLOSED_SQUARE_BRACKET = 171;
  /** RegularExpression Id. */
  int OPEN_DOUBLE_QUOTE = 172;
  /** RegularExpression Id. */
  int OPEN_PARENTHESIS = 173;
  /** RegularExpression Id. */
  int CLOSED_PARENTHESIS = 174;
  /** RegularExpression Id. */
  int OPEN_QUOTE = 175;
  /** RegularExpression Id. */
  int OPEN_TRIANGULAR_BRACKET = 176;
  /** RegularExpression Id. */
  int CLOSED_TRIANGULAR_BRACKET = 177;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<UPPER_LETTER>",
    "<LOWER_LETTER>",
    "\"_\"",
    "<ESCAPE_CHARACTERS>",
    "<SURROGATE_PAIR_CODE>",
    "<DIGIT>",
    "\"0b\"",
    "<BINARY_DIGIT>",
    "\"0o\"",
    "<OCTAL_DIGIT>",
    "\"0x\"",
    "<HEXADECIMAL_DIGIT>",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "<E>",
    "<P>",
    "\"*\"",
    "\"%\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"true\"",
    "\"false\"",
    "\"nil\"",
    "\"#file\"",
    "\"#line\"",
    "\"#column\"",
    "\"#function\"",
    "\"#colorLiteral\"",
    "\"red\"",
    "\"green\"",
    "\"blue\"",
    "\"alpha\"",
    "\"#fileLiteral\"",
    "\"#imageLiteral\"",
    "\"resourceName\"",
    "<OPERATOR_HEAD>",
    "<OPERATOR_CHARACTER>",
    "\"any\"",
    "\"->\"",
    "\"inout\"",
    "\"throws\"",
    "\"rethrows\"",
    "\"Type\"",
    "\"Protocol\"",
    "\"class\"",
    "\"try\"",
    "\"as\"",
    "\"is\"",
    "\"self\"",
    "\"init\"",
    "\"super\"",
    "<IN>",
    "\"weak\"",
    "\"unowned\"",
    "\"safe\"",
    "\"unsafe\"",
    "\"#selector\"",
    "\"getter:\"",
    "\"setter:\"",
    "\"#keyPath\"",
    "\"type\"",
    "\"of\"",
    "\" let \"",
    "\" var \"",
    "\"while\"",
    "<FOR>",
    "\"case\"",
    "\"repeat\"",
    "\"break\"",
    "\"continue\"",
    "\"if\"",
    "\"else\"",
    "\"switch\"",
    "\"default\"",
    "\"where\"",
    "\"guard\"",
    "\"fallthrough\"",
    "\"return\"",
    "\"throw\"",
    "\"defer \"",
    "\"do\"",
    "\"catch\"",
    "\"#if\"",
    "\"#elseif\"",
    "\"#else\"",
    "\"#endif\"",
    "\"os\"",
    "\"arch\"",
    "\"swift\"",
    "\"macOS\"",
    "\"iOS\"",
    "\"watchOS\"",
    "\"tvOS\"",
    "\"i386\"",
    "\"x86_64\"",
    "\"arm\"",
    "\"arm64\"",
    "\"#sourceLocation\"",
    "\"file:\"",
    "\"line:\"",
    "\"#available\"",
    "\"iOSApplicationExtension\"",
    "\"macOSApplicationExtension\"",
    "\"import\"",
    "\"typealias\"",
    "\"enum\"",
    "\"protocol\"",
    "\"func\"",
    "\"get\"",
    "\"set\"",
    "\"willSet\"",
    "\"didSet\"",
    "\"indirect\"",
    "\"struct\"",
    "\"final\"",
    "\"associatedtype\"",
    "\"deinit\"",
    "\"extension\"",
    "\"subscript\"",
    "\"prefix\"",
    "\"postfix\"",
    "\"operator\"",
    "\"precedencegroup\"",
    "\"higherThan\"",
    "\"lowerThan\"",
    "\"assignment\"",
    "\"associativity\"",
    "\"left\"",
    "\"right\"",
    "\"none\"",
    "\"convenience\"",
    "\"dynamic\"",
    "\"infix\"",
    "\"lazy\"",
    "\"optional\"",
    "\"override\"",
    "\"required\"",
    "\"static\"",
    "\"private\"",
    "\"fileprivate\"",
    "\"internal\"",
    "\"public\"",
    "\"open\"",
    "\"mutating\"",
    "\"nonmutating\"",
    "\".\"",
    "\"...\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"?\"",
    "\"!\"",
    "\"/\"",
    "\"\\\\\"",
    "\"$\"",
    "\"&\"",
    "\"&&\"",
    "\"|\"",
    "\"||\"",
    "\"@\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"\\\"\"",
    "\"(\"",
    "\")\"",
    "\"`\"",
    "\"<\"",
    "\">\"",
  };

}
